Add more robust library detection

diff --git a/pkg/ddevapp/global_dotddev_assets/commands/host/heidisql b/pkg/ddevapp/global_dotddev_assets/commands/host/heidisql
--- a/pkg/ddevapp/global_dotddev_assets/commands/host/heidisql
+++ b/pkg/ddevapp/global_dotddev_assets/commands/host/heidisql
@@ -2,8 +2,8 @@
 
 ## #ddev-generated
 ## Description: Run HeidiSQL against current db
-## Usage: heidisql [database]
-## Example: "ddev heidisql" or "ddev heidisql database2" to open a database named "database2".
+## Usage: heidisql [database] [library]
+## Example: "ddev heidisql" or "ddev heidisql database2 libpq-17.dll" to open a database named "database2" with the library "libpq-17.dll".
 ## OSTypes: windows,wsl2,linux
 ## HostBinaryExists: /mnt/c/Program Files/HeidiSQL/heidisql.exe,C:\Program Files\HeidiSQL\Heidisql.exe,/usr/bin/heidisql,/usr/local/bin/heidisql
 ## DBTypes: mysql,mariadb,postgres
@@ -15,53 +15,88 @@ if [ "${DDEV_PROJECT_STATUS}" != "running" ] && [ -z "$no_recursion" ]; then
   exit $?
 fi
 
-type="$(echo $DDEV_DATABASE | sed 's/:.*//')"
-database="${1:-db}"
-case $type in
-  "mysql" | "mariadb")
-    nettype=0
-    ;;
-  "postgres")
-    nettype=8
-    ;;
+# Determine binary
+case $OSTYPE in
+win* | msys*)
+  binary="C:\Program Files\HeidiSQL\heidisql.exe"
+  ;;
+linux-gnu)
+  BINARIES=(
+    "/usr/bin/heidisql"
+    "/usr/local/bin/heidisql"
+    "/mnt/c/Program Files/HeidiSQL/heidisql.exe"
+  )
+  for binary in "${BINARIES[@]}"; do
+    if [ -x "$binary" ]; then
+      binary="$binary"
+      break
+    fi
+  done
+  ;;
 esac
+
+# Determine database type and version
+type="$(echo $DDEV_DATABASE | sed 's/:.*//')"
+version="$(echo $DDEV_DATABASE | sed 's/.*://')"
+
+# Arguments for MariaDB/MySQL
+nettype=0
+user="root"
+password="root"
+database="${1:-db}"
+library="${2}"
+
+# Arguments for Postgres
+if [ "$type" = "postgres" ]; then
+  nettype=8
+  user="db"
+  password="db"
+  
+  # When using this database type, we also need to specify the library
+  if [ -z "${library}" ]; then
+    # For Windows and WSL2, find best matching library in the installation directory (<= version)
+    if [ "${binary##*.}" = "exe" ]; then
+      shopt -s nullglob
+      libfiles=("${binary%/*}"/libpq-*.dll)
+      shopt -u nullglob
+      for libfile in "${libfiles[@]}"; do
+        libversion="$(echo "${libfile##*/}" | sed -n 's/^libpq-\([0-9]\+\)\.dll$/\1/p')"
+        if [ -n "${libversion}" ] && [ "${libversion}" -le "${version}" ]; then
+          library="libpq-${libversion}.dll"
+        fi
+      done
+    else
+      # For Linux, check if libpq is installed
+      library=$(ldconfig -p | grep -o '/.*libpq\.so\.5' | head -n1)
+    fi
+
+    # Error if no library is found (HeidiSQL will not fail to start if no library is specified)
+    if [ -z "${library}" ]; then
+      echo "Could not find libpq library. Please install or provide a valid library."
+      exit 1
+    fi
+  fi
+fi
 
 # See: https://www.heidisql.com/help.php#commandline
 arguments=(
   "--nettype=${nettype}"
   "--host=127.0.0.1"
   "--port=${DDEV_HOST_DB_PORT}"
-  "--user=db"
-  "--password=db"
+  "--user=${user}"
+  "--password=${password}"
   "--databases=${database}"
   "--description=ddev-${DDEV_PROJECT}"
+  "${library:+--library=${library}}"
 )
 
-if [ "$nettype" -eq 8 ] ; then
-  if [ "$OSTYPE" = "win*" ] || [ "$OSTYPE" = "msys*" ] || ( [ "$OSTYPE" = "linux-gnu" ] && [ ! -x "/usr/local/bin/heidisql" ] && [ ! -x "/usr/bin/heidisql" ] ); then
-    arguments+=("--library=libpq-17.dll")
-  else
-    arguments+=("--library=/lib/x86_64-linux-gnu/libpq.so.5")
-  fi
-fi
-
-
+# Launch HeidiSQL
 case $OSTYPE in
 win* | msys*)
-  start "" "C:\Program Files\HeidiSQL\heidisql.exe" "${arguments[@]}" &
+  start "" "${binary}" "${arguments[@]}" &
   ;;
 
 linux-gnu)
-  BINARIES=(
-    "/usr/local/bin/heidisql"
-    "/usr/bin/heidisql"
-    "/mnt/c/Program Files/HeidiSQL/heidisql.exe"
-  )
-  for binary in "${BINARIES[@]}"; do
-    if [ -x "$binary" ]; then
-      "$binary" "${arguments[@]}" &>/dev/null & disown
-      break
-    fi
-  done
+  "${binary}" "${arguments[@]}" &>/dev/null & disown
   ;;
 esac
