Switch to single dockergen approach so everything gets done before nginx reload

diff --git a/containers/ddev-router/gen-cert.sh.tmpl b/containers/ddev-router/gen-cert.sh.tmpl
--- a/containers/ddev-router/gen-cert.sh.tmpl
+++ b/containers/ddev-router/gen-cert.sh.tmpl
@@ -2,13 +2,19 @@
 set -eu -o pipefail
 set -x
 
-{{ if .Env.USE_LETSENCRYPT }}
-hostnames="{{ range $host, $containers := groupByMulti $ "Env.VIRTUAL_HOST" "," }}{{ trim $host }} {{ end }}"
+if [ ! -z "${USE_LETSENCRYPT:-}" ]; then
+  hostnames="{{ range $host, $containers := groupByMulti $ "Env.VIRTUAL_HOST" "," }}{{ trim $host }} {{ end }}"
 
-for host in ${hostnames}; do
-  certbot --nginx certonly -n --domain "${host}" --agree-tos --email {{ .Env.LETSENCRYPT_EMAIL }}
-done
-{{ end }}
+  for host in ${hostnames}; do
+    # certbot challenge can fail for many reasons, but don't let it break everything
+    certbot --nginx certonly -n --domain "${host}" --agree-tos --email "${LETSENCRYPT_EMAIL:-}" || true
+  done
+fi
 
 # mkcert is fully capable of generating all needed names in a single container.
 mkcert -cert-file /etc/nginx/certs/master.crt -key-file /etc/nginx/certs/master.key {{ range $host, $containers := groupByMulti $ "Env.VIRTUAL_HOST" "," }} {{ trim $host }} {{ end }} 127.0.0.1 localhost "*.ddev.local" "*.ddev.site"
+
+# This is not recursive, as it executes completely different instructions.
+# It's important for the nginx config creation and the nginx reload to take place after all cert
+# activities are completed.
+docker-gen -only-exposed -notify-output -notify "sleep 1 && nginx -s reload" /app/nginx.tmpl /etc/nginx/conf.d/default.conf
